Integrated reducers🎯
CobbyElsonfx/bookstore-CMS pull request #2
Opened 2023-09-07 18:27 UTC by CobbyElsonfx

## In this PR I implemented the following:

###  **Project requirements**
- [ ] Add Redux Toolkit (npm install react-redux @reduxjs/toolkit).
- [ ] Create a directory that will contain all your Redux logic (/src/redux)
- [ ] Configure a Redux store (/src/redux/store.js)
 - [ ] Define a slice of state for books that:
-  Includes an array of books (initial state: empty array)
-  Includes a reducer that adds a book
-  Includes a reducer that removes a book
- [ ] Define a slice of state for categories that:
-  Includes an array of categories (initial state: empty array)
-  Includes a reducer that checks the status and always returns "Under construction" (the initial state should check to that string)

2023-09-07 19:20 UTC, shahadat3669 requested changes
Hi @CobbyElsonfx, 

Great job so far! 👏 You've done well, and you're almost there for the next project ⏭️, but there are a few issues 🐛 that you still need to work on.

<img  src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif" />


## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights

✅ Follow the ducks pattern.
✅ Imports `configureStore `from `@reduxjs/toolkit`
✅ Creates 2 reducers, `addBook` and `removeBook`


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-07 19:20 UTC, shahadat3669 commented on src/redux/books/booksSlice.jsx
> +// };
👍 Thank you for your hard work! I genuinely appreciate your dedication to learning and improving the project. I understand that there were many changes required to meet the project requirements, and it's entirely normal to take things one step at a time.

- [ ] I noticed that there is some commented-out code present in your codebase. It's generally not considered good practice to keep commented code. If the commented code is not necessary or is no longer in use, I would recommend completely deleting it to keep your codebase clean and maintainable. Keep up the fantastic work! 🌟🚀💻

2023-09-07 19:20 UTC, shahadat3669 commented on src/initialItems.jsx
👍 Great job! Your Redux store is functioning smoothly.
- [ ] However, I noticed that there is some code and files that are no longer in use. It's generally not considered good practice to keep code or files that are not useful for the project in the current situation. If the code or files are unnecessary or no longer in use, I would recommend completely deleting them to keep your codebase clean and maintainable.

By removing unused code and files, you'll ensure that your project remains organized and easier to manage. Keep up the fantastic work! 🌟🚀💻

2023-09-07 19:20 UTC, shahadat3669 commented on src/bookItems.jsx
👍 Great job! Your Redux store is functioning smoothly.
- [ ] However, I noticed that there is some code and files that are no longer in use. It's generally not considered good practice to keep code or files that are not useful for the project in the current situation. If the code or files are unnecessary or no longer in use, I would recommend completely deleting them to keep your codebase clean and maintainable.

By removing unused code and files, you'll ensure that your project remains organized and easier to manage. Keep up the fantastic work! 🌟🚀💻

2023-09-07 19:20 UTC, shahadat3669 commented on src/components/Form.jsx
> +  const id = books.length + 1;
Well! Your `addBook()` method and `removeBook()` method are indeed working fine. However, there's a slight issue currently occurring that we need to address.

- [ ] Currently, you are generating book IDs by using the length of the `books` array. While this approach initially works, it introduces a potential bug. For example, after adding two books, where the first book has ID 1 and the second book has ID 2:

```javascript
{
  books: [
    {
      id: 1,
      title: 'first book',
      author: 'author',
      category: 'action'
    },
    {
      id: 2,
      title: 'second book',
      author: 'author',
      category: 'action'
    }
  ]
}
```

- [ ] If you delete the first book and then add a new book, due to the current implementation, the newly added book will also have the same ID, 2, which already exists in the Redux store:

```javascript
{
  books: [
    {
      id: 2,
      title: 'second book',
      author: 'author',
      category: 'action'
    },
    {
      id: 2,
      title: 'third book',
      author: 'author',
      category: 'action'
    }
  ]
}
```

- [ ] As a result, if you try to delete any book, it will delete both, which is not the desired behavior.

[React-App (1).webm](https://github.com/CobbyElsonfx/bookstore/assets/55840999/acb79cf0-a71a-499f-b65b-6de31eefdf22)


To resolve this issue, you should improve your code to ensure that the generated IDs are unique. This way, you can prevent this error from occurring in the future. For example, you could use a unique identifier generator like UUIDs to generate unique IDs for your books. This would ensure that each book has a distinct and unambiguous identifier, preventing such conflicts.

By making this adjustment, you'll enhance the robustness of your code and prevent potential issues with duplicate IDs. Keep up the great work! 🌟📚

2023-09-08 02:29 UTC, Reem-lab approved these changes
# Hi @CobbyElsonfx,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [ ]  Followed Gitflow 💯
- [ ]  Descriptive PR⭐
- [ ]  Kudos for working on the functionality🤩
- [ ]  No Linters error ✅




## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-08 02:33 UTC, merged